USE UNIVER;
--№1
SELECT FACULTY.FACULTY[Факультет], PULPIT.PULPIT_NAME[Кафедры], PROFESSION.PROFESSION_NAME[Технологические специальности]
		FROM FACULTY, PULPIT, PROFESSION
		WHERE FACULTY.FACULTY = PULPIT.FACULTY AND FACULTY.FACULTY = PROFESSION.FACULTY
		AND
		PROFESSION.PROFESSION_NAME In(SELECT PROFESSION.PROFESSION_NAME FROM PROFESSION 
									WHERE (PROFESSION.PROFESSION_NAME LIKE '%технологи%'))

--№2
SELECT FACULTY.FACULTY[Факультет], PULPIT.PULPIT_NAME[Кафедры], PROFESSION.PROFESSION_NAME[Технологические специальности]
		FROM FACULTY
		Inner Join PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
		Inner Join PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
		WHERE PROFESSION_NAME In(SELECT PROFESSION.PROFESSION_NAME FROM PROFESSION 
											WHERE (PROFESSION.PROFESSION_NAME LIKE '%технологи%'))

--№3
SELECT FACULTY.FACULTY[Факультет], PULPIT.PULPIT_NAME[Кафедры], PROFESSION.PROFESSION_NAME[Технологические специальности]
		FROM FACULTY
		Inner Join PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
		Inner Join PROFESSION ON FACULTY.FACULTY = PROFESSION.FACULTY
		WHERE (PROFESSION_NAME LIKE '%технологи%')
---№4
SELECT AUDITORIUM_TYPE[Тип аудитории],AUDITORIUM_CAPACITY[Вместимость] FROM AUDITORIUM a
			WHERE AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM aa
				WHERE aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
				ORDER BY AUDITORIUM_CAPACITY desc)

---№5
SELECT FACULTY.FACULTY_NAME[Наименование факультета], PULPIT.PULPIT[Кафедра] 
		FROM FACULTY, PULPIT
			WHERE not exists (SELECT * FROM PULPIT WHERE FACULTY.FACULTY = PULPIT.FACULTY)

select FACULTY.FACULTY_NAME, PULPIT.PULPIT[Кафедра] from FACULTY, PULPIT
	where exists (select * from PULPIT where FACULTY.FACULTY = PULPIT.FACULTY)

---№6
SELECT top 1
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS
			WHERE PROGRESS.SUBJECT like 'ОАиП') [Средняя по ОАиП],
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS
			WHERE PROGRESS.SUBJECT like 'КГ') [Средняя по КГ],
	(SELECT avg(PROGRESS.NOTE) FROM PROGRESS
			WHERE PROGRESS.SUBJECT like 'СУБД') [Средняя по СУБД]
	FROM PROGRESS

---№7
SELECT SUBJECT, NOTE FROM PROGRESS
	WHERE NOTE >=ALL (SELECT NOTE FROM PROGRESS
						WHERE SUBJECT like 'ОАиП')

---№8
SELECT SUBJECT, NOTE FROM PROGRESS
	WHERE NOTE >=ANY (SELECT NOTE FROM PROGRESS
						WHERE SUBJECT like 'ОАиП')
---№10
SELECT STUDENT.NAME, STUDENT.BDAY FROM STUDENT
	WHERE BDAY IN(SELECT STUDENT.BDAY FROM STUDENT
						GROUP BY STUDENT.BDAY
						HAVING (count(STUDENT.BDAY) > 1))
						ORDER BY STUDENT.BDAY